print("#1----------------")
tup = ("dog", "cats", "fish")
print(tup)
print("#2----------------")
word = ("f", "e", "r", "n", "a", "n")
print(word[0:4])
print("#3----------------")
city = ("butuan city", "davao city", "cebu city")
for cities in city:
    print(cities.title())
print("#4----------------")
snack = ("Spaghetti", "Siomai", "Taco")
print("snacks available:")
for index, snacks in enumerate(snack, start=1):
    print(index, snacks)
print("#5----------------")
snack2 = ("Spaghetti", "Siomai", "Taco")
enter_snack = input("What snacks do you like(Available: 0-Spaghetti, 1-Siomai, 2-Taco? Choose by number:")
print(snack2)
entered = int(enter_snack)
get_snack = snack2[entered]
print(get_snack, "has been ordered")
print("#6----------------")
animals = ("duck", "dogs", "skunk", "dogs")
cnt = animals.count("dogs")
print("there are", cnt, animals[1])
print("#7----------------")
animals2 = ("duck", "dogs", "skunk", "dogs", "cat")
print("choose from this list:", animals2)
enter_animal = input("Enter animal:")
get_index = animals2.index(enter_animal)
print("Your animal is at index", get_index)

